### ISSUE TITLE
Read harvest auth credentials from AWS secret manager 

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#100]
### 💡 Description

Currently harvest tool is reading auth credentials to connect OpenSearch from a configuration file in file system. Nucleus uses a dockerized version of harvest too. It is required to implement a way to read these harvest auth credentials from AWS Secret Manager.

**Comment by jordanpadams** [comment]
Status: Issues trying to access secrets manager.

**Comment by ramesh-maddegoda** [comment]
I was able to implement this by reading Opensearch credentials from AWS secret manager and create a credential file inside the temporary docker container to be used by harvest.

The changes were added to the pull request https://github.com/NASA-PDS/nucleus/pull/98
