### ISSUE TITLE
Integrate the latest version 4.0.1 of harvest in Nucleus workflow

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#121]
### 💡 Description

Recently there were lots if changes happened in harvest related with the Cognito authentication and accessing Open Search. This task is to integrate the latest version 4.0.1 of harvest in Nucleus workflow

**Comment by ramesh-maddegoda** [comment]
Expecting new changes to be implemented  in harvest, when using it in a VPC inside MCP Dev.

**Comment by tloubrieu-jpl** [comment]
blocked by  ticket https://github.com/NASA-PDS/registry-common/issues/83

**Comment by jordanpadams** [comment]
Standup status: Testing this out now .

**Comment by tloubrieu-jpl** [comment]
I have fixed the registry-loader docker image that @ramesh-maddegoda was working with to use a version of harvest which supports to get the AWS credentials from the AWS assumed role.
However I have not been able to make that work on EC2 following manual https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html. An alternative could be to deploy on ECS where this method has already been successfully tested for the registry API.

Another option is to wait for the SA's to solve the ticket DSIO-6578 in which we ask to be able to access the API gateway from E2 or ECS.

We should keep working on both options in parallel.

**Comment by tloubrieu-jpl** [comment]
Ramesh will work on the ECS deployment, using the URL http://169.254.170.2/AWS_CONTAINER_CREDENTIALS_RELATIVE_URI in the connection configuration, as documented in https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda is making progress on that. He can use the latest Docker proposed but updates need to be done in nucleus to support the latest configuration format.

**Comment by tloubrieu-jpl** [comment]
harvest now runs, Ramesh will validate that it behave properly.

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda validated that it works, he is now cleaning the code and @tloubrieu-jpl needs to merge the PR which enable harvest to work from ECS as tested successfully by Ramesh.

**Comment by tloubrieu-jpl** [comment]
There was an issue while override the entrypoint of the Docker image in ECS. Ramesh solved it and is now testing the full nucleus deployment.

**Comment by ramesh-maddegoda** [comment]
Created pull request: https://github.com/NASA-PDS/nucleus/pull/132

**Comment by ramesh-maddegoda** [comment]
Merged pull request: https://github.com/NASA-PDS/nucleus/pull/132

**Comment by tloubrieu-jpl** [comment]
The cognito user/password does not matter in this config.

**Comment by tloubrieu-jpl** [comment]
nucleus is now pushing the harvest docker image from dockerHub to ECR.
