### ISSUE TITLE
Complete JPL Internal Peer Review of Trade Study and Technology Selection

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#19]

**Comment by jordanpadams** [comment]
Review scheduled for 12/15

**Comment by tloubrieu-jpl** [comment]
The review happened today and the board validated our choice.

**Comment by jordanpadams** [comment]
documents presented at review:

Slides: https://docs.google.com/presentation/d/1xbaJQ6e9jg3XZn2VXsfygKlUMZ_gW4c_t65Vkq0daKI/edit#slide=id.g12d488fa3c5_0_132
Trade Study Spread Sheet:https://docs.google.com/spreadsheets/d/17Yxf1m6f4VvLd6QFuqJADAhwKPhqQnQemtMb9MqWyDI/edit#gid=1611047106
Requirements: https://github.com/NASA-PDS/nucleus/blob/main/docs/requirements/REQUIREMENTS.md
PDS Nucleus Architecture: https://lucid.app/lucidchart/81986f34-dcad-4f2a-8f79-ae1e3a9f4572/edit?viewport_loc=493%2C-970%2C4451%2C2451%2C0_0&invitationId=inv_8875db52-fe0d-40f7-af95-0ad857d40e34
