### ISSUE TITLE
As a user, I want to deploy a baseline nucleus automatically.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#22]
## 🧑‍🔬 User Persona(s)

Sys Admin

## 💪 Motivation
...so that I can automatically deploy a new baseline nucleus instance with minimal manual intervention.

## 📖 Additional Details

- [x] Terraform scripts for deploying in AWS (deploy.sh?)
- [ ] Docker container for local deployment (It was decided to use MWAA on AWS and a local deployment is not applicable with MWAA)
- [x] Document any manual requirements

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
Status: To be wrapped up by Thursday

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda solved a security issue when launching tasks on ECS.

**Comment by ramesh-maddegoda** [comment]
Blocker: Cannot see any of the Managed Airflow environments (MWAA) created on NGAP anymore. Also, it seems we have lost MWAA related terraform access on this account.
  
```
Terraform Error: error reading MWAA Environment (basic-mwaa): AccessDeniedException: ..... not authorized to perform: airflow:GetEnvironment on resource
```

Possible Cause: The NGAP team has recently deployed some Service Control Policies for NGAP environments and that may have affected the access. 

Currently waiting for NGAP team to resolve this.

**Comment by ramesh-maddegoda** [comment]
The NGAP OPS team has fixed the permission issue. Ramesh is currently updating terraform scripts to fix a S3 bucket policy related permission issue.

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda still has permission issues of different kinds, not blocked though

**Comment by ramesh-maddegoda** [comment]
Created a pull request for Terraform script of Nucleus baseline system (MVP).
https://github.com/NASA-PDS/nucleus/pull/40

The Terraform scripts in this pull request deploy a minimum viable product (MVP) of PDS Nucleus data pipeline system on AWS Cloud. Currently, Nucleus is based on Amazon Managed Workflows for Apache Airflow (MWAA). Therefore, as a result of the Terraform scripts in this directory following things will be created.

- AWS Security Group for MWAA
- AWS S3 Bucket with relevant bucket policies to keep Airflow DAG files and Python requirements file
- Dags directory in S# bucket to keep Airflow DAG files
- Python requirements.txt file to introduce the additional Python packages required by DAGs
- Amazon Managed Workflows for Apache Airflow (MWAA)

Note: In addition to the above components, there are Terraform modules, container definitions and a DAG file ncluded to deploy PDS Registry related ECS tasks, a DAG and an EFS file system that can be used to demonstrate an example PDS Registry use case. However, these additional components are not part of the MVP of PDS Nucleus data pipeline. These PDS Registry related terraform modules are still under development (not part of the PDS Nucleus Baseline Deployment task) and are kept disabled in the main.tf terraform file.
