### ISSUE TITLE
As a user, I want to estimate the cost for a new deployment

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#27]
## 🧑‍🔬 User Persona(s)

Node Manager

## 💪 Motivation
...so that I can accurately measure how much it will cost for a baseline Nucleus deployment

## 📖 Additional Details

 - [x] Baseline Nucleus Cost Model
 - [x] Cost Modeling User Guide

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
@ramesh is writing the user guide for the cost model.

**Comment by ramesh-maddegoda** [comment]
The initial draft of user guide is available as a sheet in the same cost model related Google sheet https://docs.google.com/spreadsheets/d/1sLobcbMgigQ0mjNesU-qDQUOj52RWETG0m-V1nUitSY/edit?usp=sharing

**Comment by ramesh-maddegoda** [comment]
The user guide and cost model are completed.
