### ISSUE TITLE
As a user, I want to know the baseline architecture and deployment

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#29]
## 🧑‍🔬 User Persona(s)

Node Operator

## 💪 Motivation
...so that I can understand what Nucleus is, the baseline tools and services included in the deployment, and what this is all for.

## 📖 Additional Details

-  [ ] Nucleus Intro User Guide

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jimmie** [comment]
defining minimal set of necessary components for 'standard' use cases + pricing considerations.

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda proposed a document for the architecture on g-drive.

**Comment by tloubrieu-jpl** [comment]
Prepared the following Google Doc to address this ticket. Did not use Markdown or reStructuredText yet.
https://docs.google.com/document/d/1ONUhSJhxJmMt09H-fbfBRl2N-l_02E-CeylmEe_hpAg/edit#

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda work on the conversion to RST
