### ISSUE TITLE
Evaluate self-managed airflow with ECS and Fargate for Nucleus

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#33]
The Amazon Managed Workflows for Apache Airflow (MWAA) has some ongoing costs due to the always up and running Airflow UI. There is no option available to suspend the MWAA environment when it is not in use.

This task is to evaluate the self-managed airflow with ECS and Fargate as an alternative to MWAA to reduce the operating cost of Nucleus.

**Comment by ramesh-maddegoda** [comment]
Advantages:

- Ability to horizontally scale without limiting to the number of workers and schedulers specified by Amazon MWAA environment classes
- Possible to shutdown the environment to save costs
- More control over the AWS services (ECS services etc.)
- Ability to use the latest versions of Airflow

Disadvantages:

- Initial setup can be time consuming (this infrastructure should be scripted with terraform to make it reusable) 
- Self managed and need to maintain the services

**Comment by jordanpadams** [comment]
Status: Added some advantages/disadvantages right there ☝️
