### ISSUE TITLE
Evaluate the self-managed airflow on AWS EKS

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#34]
The Amazon Managed Workflows for Apache Airflow (MWAA) has some ongoing costs due to the always up and running Airflow UI. There is no option available to suspend the MWAA environment when it is not in use.

This task is to evaluate the self-managed airflow on AWS EKS as an alternative to MWAA to reduce the operating cost of Nucleus.

**Comment by ramesh-maddegoda** [comment]
Advantages:

- Ability to use community provided Airflow helm charts (https://airflow.apache.org/docs/helm-chart/stable/index.html)
- Portable to non AWS environments that support Kubernetes

Disadvantages:

- Users pay a hourly price for each Amazon EKS cluster
- The deployment is complicated compared to ECS
- Operators and developers will need to have a good understanding of these various components and how they interact to optimize Kubernetes applications.


</div></b>

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda is deploying a pilot for that on AWS, waiting for Jason response now.

**Comment by ramesh-maddegoda** [comment]
- An EKS cluster was created to deploy Airflow on EKS.
- Airflow components (including airflow-postgresql, airflow-redis, airflow-scheduler, airflow-webserver and airflow-worker) were deployed using Airflow helm charts.
- The resources were deployed but were pending due to the unavailable EKS node group (Sent an email to NGAP team to get a new IAM role created for node groups). However it is not a blocker to evaluate deploying Airflow on EKS.

References: 

- https://gist.github.com/kppullin/54d07f557c7c64c321786d6ed40b46e1
- https://towardsdatascience.com/setting-up-airflow-on-aws-eks-385667671789
- https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/guides/quickstart.md
- https://airflow.apache.org/docs/helm-chart/stable/index.html


Also, during this evaluation the choice of Airflow executers appeared as an important decision. Using Kubernetes will enable us to use Kubernetes Executor or CeleryKubernetes Executor. Using a Kubernetes based executer allows us to have a more cost effective horizontal scalability in times of low traffic, giving the ability to scale to zero.

References:

- https://docs.astronomer.io/learn/airflow-executors-explained
- https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/index.html 
- https://medium.com/international-school-of-ai-data-science/executors-in-apache-airflow-148fadee4992
