### ISSUE TITLE
Evaluate the self-managed airflow on AWS EC2

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#35]
The Amazon Managed Workflows for Apache Airflow (MWAA) has some ongoing costs due to the always up and running Airflow UI. There is no option available to suspend the MWAA environment when it is not in use.

This task is to evaluate the self-managed airflow on AWS EC2 as an alternative to MWAA to reduce the operating cost of Nucleus.

**Comment by ramesh-maddegoda** [comment]
Advantages:

- Very simple deployment approach where each components of Airflow will be deployed on EC2 instances
- Easy to manage

Disadvantages:

- The scalability is very low and cannot handle unexpected load spikes
- Self managed and need to maintain the services

**Comment by jordanpadams** [comment]
Status: Advantages/disadvantages added here ☝️
