### ISSUE TITLE
Evaluate options to backup and restore the metadata database and logs of MWAA

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#36]
The Amazon Managed Workflows for Apache Airflow (MWAA) has some ongoing costs due to the always up and running Airflow UI. There is no option available to suspend the MWAA environment when it is not in use.

This task is to evaluate options to backup and restore the metadata database and logs of MWAA to reduce the operating cost of Nucleus.

**Comment by jordanpadams** [comment]
Status: Still in work to see if this is an option. Not much information found thus far.

**Comment by ramesh-maddegoda** [comment]
The following guide discusses about migrating a self-managed Apache Airflow workflows to Amazon MWAA, or upgrade an existing Amazon MWAA environment to a new Apache Airflow version.
https://docs.aws.amazon.com/mwaa/latest/migrationguide/about-mwaa-migration.html

**Comment by ramesh-maddegoda** [comment]
This approach is not a very practical approach in production compared to the other Airflow deployment approaches such as Airflow on EKS or ECS.
