### ISSUE TITLE
Prepare cost model for Nucleus - Considering Amazon Managed Airflow (Amazon MWAA)

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#37]
It was decided to consider the Amazon Managed Airflow (Amazon MWAA) for short term for Nucleus and later consider a more flexible approach such and self managed Airflow in future. This task is to prepare the cost model document considering Amazon MWAA.

**Comment by ramesh-maddegoda** [comment]
Created the draft cost mode (to be reviewed and improved).

**Comment by ramesh-maddegoda** [comment]
DRAFT Nucleus Cost Model
https://docs.google.com/spreadsheets/d/1sLobcbMgigQ0mjNesU-qDQUOj52RWETG0m-V1nUitSY/edit?usp=sharing

**Comment by jordanpadams** [comment]
this is done for now. to review the trade study, but the cost model is sufficient for the time being

**Comment by jordanpadams** [comment]
@ramesh-maddegoda to verify when it comes to Nucleus, when we want to execute something like validate on a data products using some files on a file system, do we need to pay for the EC2 or whatever other services the workflow task needs to execute? or is that included in Airflow?

**Comment by ramesh-maddegoda** [comment]
> @ramesh-maddegoda to verify when it comes to Nucleus, when we want to execute something like validate on a data products using some files on a file system, do we need to pay for the EC2 or whatever other services the workflow task needs to execute? or is that included in Airflow?

@jordanpadams , that cost is covered as the cost for "Amazon Elastic Container Service (Amazon ECS) with Fargate Launch Type". Because the actual PDS docker containers will be executed as ECS tasks. Airflow will delegate the load to ECS tasks. This is the "Task" related costs shown in line 18 to 20 in [cost model ](https://docs.google.com/spreadsheets/d/1sLobcbMgigQ0mjNesU-qDQUOj52RWETG0m-V1nUitSY/edit#gid=0 ).

The details of costs for each PDS Docker container (ECS task) is calculated from line 32 to 40 in [cost model ](https://docs.google.com/spreadsheets/d/1sLobcbMgigQ0mjNesU-qDQUOj52RWETG0m-V1nUitSY/edit#gid=0 )

**Comment by jordanpadams** [comment]
thanks @ramesh-maddegoda sorry for my lack of understanding here. thanks for taking the time to educate me :-)
