### ISSUE TITLE
Create a user guide to create new DAGs

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/nucleus#43]
## 💡 Description

Publish it in the sphynx documentation.

**Comment by jordanpadams** [comment]
status: in progress as a tutorial. @viviant100 onboard for testing it out.

@jordanpadams to provide some use cases we received from GEO

**Comment by jordanpadams** [comment]
@ramesh-maddegoda here are some specific examples of use cases from nodes that include some manual curation/inspection steps: https://drive.google.com/drive/u/1/folders/1uPOSwtMjK_jFxC72c2U7Dv1h5_EfscBr

**Comment by jordanpadams** [comment]
status: tutorial in work

**Comment by tloubrieu-jpl** [comment]
Prposed guide: https://docs.google.com/document/d/1ewjPa8hVEMigCIbgtYTd1RqgnpdIR20gQ5a7chn-6Po/edit#heading=h.bmqu50lwr7nk

We will discuss the options to simplify the user guide proposed during the breakout

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda Per the breakout discussion, the user guide will be finalized with the available technical options (e.g. EFS for sharing data), be published on gh-pages with sphynx with 2 tutorials: 
1. user: create/run DAGs, 
2. sys admin: create new services/operator (being available to be used in DAGs).

I am thinking now, that we might need to document somewhere, the service (operators) that can be used in Nucleus.

**Comment by ramesh-maddegoda** [comment]
Created the pull request https://github.com/NASA-PDS/nucleus/pull/47 with the tutorial
