### ISSUE TITLE
Evaluate the ability to create Nucleus workflow using CWL (Common Workflow Language)

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#51]
## 🧑‍🔬 User Persona(s)

Node Operator

## 💪 Motivation
...so that I can use an open workflow definition standard encouraged by NASA to define Nucleus workflows.

## ⚖️ Acceptance Criteria
Working example of a Nucleus workflow created with CWL

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda sent a message to AWS but did not get an answer yet

**Comment by ramesh-maddegoda** [comment]
Answers received:

Is it possible to use Common Workflow Language (CWL) with MWAA? Is it possible to use CWL-Airflow with MWAA?
- CWL-Airflow seems to be pretty old (was done for 2.1.4).  Expect issues using it with newer versions of Airflow, let alone trying to get it to work with MWAA. 
 
Are there any other standard notations (E.g.: BPMN) currently supported by MWAA or are there any future plans to support?
- Not at the moment
