### ISSUE TITLE
Work with IMG to connect to S3 Bucket with MESSENGER data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#52]
## 💡 Description

- Contact @thareusgs to discuss getting access without downloading:
https://asc-pds-messenger.s3.us-west-2.amazonaws.com/
   * We should probably just replicate this data to a temporary staging bucket for processing, and then drop it for now until we move to a production MCP with appropriate budget allocated.

```
> aws s3 ls --no-sign-request s3://asc-pds-messenger
                           PRE MESSDEM_1001/
                           PRE MSGRMDS_1001/
                           PRE MSGRMDS_2001/
                           PRE MSGRMDS_3001/
                           PRE MSGRMDS_4001/
                           PRE MSGRMDS_5001/
                           PRE MSGRMDS_6001/
                           PRE MSGRMDS_7001/
                           PRE MSGRMDS_7101/
                           PRE MSGRMDS_7201/
                           PRE MSGRMDS_7301/
                           PRE MSGRMDS_8001/
```
- [ ] Document how we can replicate "external" S3 buckets into a staging bucket

**Comment by thareUSGS** [comment]
IMG also lives at JPL, perhaps Myche can help using JPL's S3 resources for now...

When EN wants to host some of our S3 data, I am all for it. :-)

**Comment by tloubrieu-jpl** [comment]
Works with a public bucket but not with a private one. The access key is not known from s3.

**Comment by tloubrieu-jpl** [comment]
Access to s3 now works.

@ramesh-maddegoda is copying the MESSENGER s3 bucket to our own s3 bucket to avoid costs on  the providers s3.

**Comment by nutjob4life** [comment]
Issue w/Airflow on NGAP: Must check with Jason. Airflow NWAA env fails to start new [indistinct]. Tried to create new env; but get "subnets should have more than 8 IP addresses available", and "you do not have perms to modify VPNs". Deleted env to release IPs, re-created, but getting same error re IP addresses. NGAP limitation? Jason to the rescue.

**Comment by ramesh-maddegoda** [comment]
We had a call with Jason about the MWAA errors on NGAP. He said they recently introduced some policy changes on NGAP and that can be the reason for this. Jason is going to troubleshoot that further and find a fix.

**Comment by nutjob4life** [comment]
Partially blocked; email sent to Jason to see if he can check the issue. Need to be allowed to create NWAA—hence, partially blocked. Considering discussion from last week on how to process data. One challenge: unlike S3, we do not have granularity with EFS SS3 (?) … it's like the medium between two tasks. Need to identify a file copy set. Will come up with a different design based on what we discuss—especially EFS and events.

**Comment by tloubrieu-jpl** [comment]
Ramesh created a lambda to copy the IMG data to our S3.

**Comment by tloubrieu-jpl** [comment]
We want to harvest 2 collections as soon as we can, in IMG node not using nucleus since it is blocked.
