### ISSUE TITLE
Avoid stale data due to race conditions in Nucleus DynamoDb tables used by product completion checker lambda

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#65]
It was identified that race conditions can happen while multiple S3 event notifications invoke lambda to update DynamoDB tables (reference https://github.com/NASA-PDS/nucleus/issues/63 ). 

To avoid that, a locking mechanism should be implemented.

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda is reading on lock management on dynamodb

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda started to implement a lock system proposed by dynamodb by adding a version number to the record. He is now testing the implementation.

**Comment by ramesh-maddegoda** [comment]
@tloubrieu-jpl , The following articles are explaining about DynamoDB locks using a version number. In my implementation, I am using the last updated timestamp as the version number to make sure the record is not updated  by another thread.

Amazon DynamoDB - Optimistic locking with version number (Java examples)
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html

DynamoDB Optimistic vs Pessimistic Locking [The Ultimate Guide]
https://dynobase.dev/dynamodb-locking/

Also, for above approaches we have to use DynamoDB conditional expressions (E.g: Conditional updates)

Amazon DynamoDB - Condition expressions
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html

**Comment by tloubrieu-jpl** [comment]
works with small datasets but expected files remains unexpectedly for bigger datasets.

**Comment by tloubrieu-jpl** [comment]
Now @ramesh-maddegoda works with a RDS/mySQL back-end instead of dynamoDB since we were unable to properly set locks to avoid the race conditions.

**Comment by ramesh-maddegoda** [comment]
Came up with an RDS based approach where we use 2 lambda functions.
1. pds-nucleus-product-writer.py - To write files to EFS and store file names to RDS tables when we receive files
2. pds-nucleus-product-completion-checker.py - To check the completion status of products and notify completed products to an SQS queue (will be triggered on a schedule- E.g.: Every 3 minutes)

Pull request: https://github.com/NASA-PDS/nucleus/pull/70

**Comment by tloubrieu-jpl** [comment]
There are still time out when the copy to EFS takes too long (>15minutes).

**Comment by jordanpadams** [comment]
Status: @ramesh-maddegoda going to update to include PEP-8 on PR

**Comment by jordanpadams** [comment]
@ramesh-maddegoda is this closed by #70 ?

**Comment by ramesh-maddegoda** [comment]
> @ramesh-maddegoda is this closed by #70 ?

Yes @jordanpadams ,that is correct.
