### ISSUE TITLE
Setting-up MWAA Environment on MCP

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#68]

**Comment by tloubrieu-jpl** [comment]
Manula deployment was succesfully tested. @ramesh-maddegoda will now test the deployment with terraform

**Comment by ramesh-maddegoda** [comment]
Completed setting up baseline MWAA on MCP using the terraform scripts. Made few improvements to the terraform scripts.
https://github.com/NASA-PDS/nucleus/pull/69
