### ISSUE TITLE
Support CSS demo 

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/nucleus#71]

**Comment by jordanpadams** [comment]
Status: Ran into issues with MWAA and product level execution, but discussed with THomas and Jordan and has path forward

**Comment by jordanpadams** [comment]
Status: Some data uploaded, but ran into issues with `.fits` files not being found in S3 bucket.

**Comment by jordanpadams** [comment]
Demo completed 10/27
