### ISSUE TITLE
As a user, I want to store a copy of my archive data in AWS Deep Archive / Glacier

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#73]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Archivist

### 💪 Motivation

...so that I can have a copy of my data available in the event of corruption or disaster recovery

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect** 

### ⚙️ Engineering Details

Tightly coupled with cloud requirement: https://github.com/NASA-PDS/planetary-data-cloud/issues/75

**Comment by viviant100** [comment]
tagup with MCP - we (PDS) will be able to set up glacier ousevles.

**Comment by viviant100** [comment]
@ramesh-maddegoda At monthly MCP meeting today (7/8/24), we explored the following options instead of using glaciers:
- Enabling S3 bucket versioning
- Utilizing multi-region S3 buckets

Could you please evaluate these approaches with Nucleus?

**Comment by jordanpadams** [comment]
@viviant100 poking at [this a bit online](https://aws.amazon.com/s3/features/replication/), I think what the folks on the MCP call may have been referring to was [Cross-Region Replication](https://aws.amazon.com/s3/features/replication/). We could then:

* Replicate the data from our S3 archive bucket to another region
* Once the data is replicated to the other region, move it to Deep Archive tier

To kick off this effort, can you help with a couple sub-tasks:
- [ ] Provide a cost comparison of our existing planned costs for a copy of the data in S3 and Glacier vs. S3 + versioning + cross-region replication + Deep Archive (we can use lower storage tier since we have versioning enabled)
- [ ] Ask around to other data repositories and archives at JPL to determine what their disaster recovery solutions are for data at rest in the cloud, and whether or not this solution seems sensible

**Comment by ramesh-maddegoda** [comment]
Now, in MCP it takes more than 2 hours sometimes to create MWAA in MCP with Terraform and it fails with the following error.
```
module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env: Still creating... [1h56m25s elapsed]
module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env: Still creating... [1h56m35s elapsed]
module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env: Still creating... [1h56m45s elapsed]
module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env: Still creating... [1h56m55s elapsed]
module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env: Still creating... [1h57m5s elapsed]
module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env: Still creating... [1h57m15s elapsed]
module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env: Still creating... [1h57m25s elapsed]
module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env: Still creating... [1h57m35s elapsed]
module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env: Still creating... [1h57m45s elapsed]
╷
│ Error: waiting for MWAA Environment (pds-nucleus-airflow-env) create: operation error MWAA: GetEnvironment, https response error StatusCode: 403, RequestID: 9c1603bb-8845-4eb1-951b-45623079b703, api error ExpiredTokenException: The security token included in the request is expired
│ 
│   with module.mwaa-env.aws_mwaa_environment.pds_nucleus_airflow_env,
│   on terraform-modules/mwaa-env/mwaa_env.tf line 57, in resource "aws_mwaa_environment" "pds_nucleus_airflow_env":
│   57: resource "aws_mwaa_environment" "pds_nucleus_airflow_env" {
│ 
 
 

``` 

Created the request https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-3804 to get long term access keys to avoid this problem.

**Comment by ramesh-maddegoda** [comment]
This ticket was unblocked after finding a solution to https://github.com/NASA-PDS/nucleus/issues/118

**Comment by ramesh-maddegoda** [comment]
Created pull request: https://github.com/NASA-PDS/nucleus/pull/119

**Comment by jordanpadams** [comment]
Status: Initially had an issue with pushing to Glacier. Need to set `--force` flag in order to overwrite the data in Glacier.

**Comment by tloubrieu-jpl** [comment]
We finally want a replication across regions and we do that using a replication rule configured in terraform (as done for the ODR bucket).

**Comment by ramesh-maddegoda** [comment]
Create a pull request https://github.com/NASA-PDS/nucleus/pull/120

**Comment by tloubrieu-jpl** [comment]
The PR is merged and next step is to document the needed configuration, a ticket will be created for that.

**Comment by jordanpadams** [comment]
This can be closed. Wrap-up of https://github.com/NASA-PDS/planetary-data-cloud/issues/75 will include the necessary documentation.
