### ISSUE TITLE
Prepare product labels as batches to be processed by Nucleus

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#75]
Initially it was decided to present PDS product-by-product to Nucleus to be processed. However, when processing larger data sets with hundreds or thousands of PDS product labels, this can lead to launch a large number of ECS tasks and docker containers, which is both time consuming and resource consuming.

It is required to implement a way to create batches of PDS product labels and present those batches as manifest files to Nucleus to be processed.

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda works now with batches of 10 products which works for validate and harvest for messenger data.

@ramesh-maddegoda will use the manifest supported by both validate and harvest for a list of products.

**Comment by tloubrieu-jpl** [comment]
Done but PR is not ready yet.

**Comment by ramesh-maddegoda** [comment]
The pull request is available at https://github.com/NASA-PDS/nucleus/pull/78
