### ISSUE TITLE
Nucleus documentation is broken

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#76]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Documentation should be https://nasa-pds.github.io/nucleus but it is not.

### 🕵️ Expected behavior

I expected the documentation to be online.

### 📜 To Reproduce

Go to https://nasa-pds.github.io/nucleus

**Comment by tloubrieu-jpl** [comment]
The round-up github actions are missing in the nucleus repository, that is why the documentation is not updated. @ramesh-maddegoda will fix that.

**Comment by ramesh-maddegoda** [comment]
Created a new GitHub actions workflow (https://github.com/NASA-PDS/nucleus/actions/workflows/build_docs.yml) and successfully automated deploying the Nucleus documentation at  https://nasa-pds.github.io/nucleus .

**Comment by jordanpadams** [comment]
@ramesh-maddegoda Documentation looks good. Looks like the `conf.py` needs to be updated (still says "My PDS Project"), but not super critical

**Comment by ramesh-maddegoda** [comment]
> @ramesh-maddegoda Documentation looks good. Looks like the `conf.py` needs to be updated (still says "My PDS Project"), but not super critical

Thanks @jordanpadams! I fixed it.
