### ISSUE TITLE
Nucleus: Track the DAG processing status of each PDS product for monitoring and troubleshooting

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/nucleus#88]
### 💡 Description

At the moments, multiple product labels are processed in Nucleus DAGs as batches. The Airflow UI shows the completion status of each batch and it is also possible to identify individual product failures in a given batch by checking task logs on Airflow UI. 

However, when we process thousands of products within a short duration, it is more efficient to keep track of the processing status of each PDS product in a central place such as a database. Also, this will allow us to easily query for failures and troubleshoot.

This task is to design and implement an approach to keep track of processing status of individual PDS products.

**Comment by tloubrieu-jpl** [comment]
Ramesh is adding a status monitoring in the nucleus RDS database, as a new table to avoid conflict with the product completion tracking.

**Comment by ramesh-maddegoda** [comment]
Created pull request: https://github.com/NASA-PDS/nucleus/pull/117

**Comment by tloubrieu-jpl** [comment]
The status for each DAG steps are stored.
It is not yet information available to the users.

**Comment by ramesh-maddegoda** [comment]
The pull request https://github.com/NASA-PDS/nucleus/pull/117 is merged.
