### ISSUE TITLE
Deploy Nucleus in Test env

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/nucleus#89]
### 💡 Description

Deploy with the least level of performance/workers possible for nucleus in Test env.  

- [x] Document deployment steps
- [x] Deploy Nucleus in test env
- [x] verify Nucleus can process CSS data from DUM

**Comment by tloubrieu-jpl** [comment]
This tasks requires to rewrite the terraform scripts.

Some other parts of the of the deployment need to be terraformed (e.g. RDS database).

**Comment by jordanpadams** [comment]
status: working on improving terraform scripts to enable this deployment

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda is making good progress on that.

**Comment by tloubrieu-jpl** [comment]
The deployment works but the DAG still have permission issues.

**Comment by jordanpadams** [comment]
Status: Adjusting roles for access. Currently testing the DAGs with lowest privileges and fixing some of those issues. No blockers. Terraform has been improved. Plan to destroy/redeploy before ready for production.

**Comment by tloubrieu-jpl** [comment]
Ramesh tested the deployment from scratch : need to launch the terraform twice because credential expires but that is ok.

**Comment by tloubrieu-jpl** [comment]
The deployment fully work expect for harvest which needs a whitelisted IP to send data to the JPL AWS OpenSearch.

**Comment by tloubrieu-jpl** [comment]
For more flexibility in the future we might have multiple nucleus instance deployed in dev and test, using a prefix for example.

**Comment by ramesh-maddegoda** [comment]
Created pull request https://github.com/NASA-PDS/nucleus/pull/97 to update Terraform scripts, IAM policy files, Lambda functions and documentation to deploy PDS Nucleus in MCP Test and Prod environments.

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda need to update the terraform README and the PR is ready for review.

**Comment by tloubrieu-jpl** [comment]
Presentation done to the SA. Review went well. Ramesh will investigate using secret manager for harvest configuration.

**Comment by jordanpadams** [comment]
Status: Continuing to evolve and update terraform code.

**Comment by ramesh-maddegoda** [comment]
Verified that Nucleus can process CSS data from DUM.
 All the terraform related changes were merged in to the main branch with the PR: https://github.com/NASA-PDS/nucleus/pull/98

**Comment by tloubrieu-jpl** [comment]
Ramesh added SQS in the terraform script to queue the lambda calls. It is tested.
