### ISSUE TITLE
CSS MVP: Deploy Baseline Nucleus for Catalina Sky Survey in Test and Production Environments

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#93]
### 💡 Description

Need a clean deployment ready for CSS in Test and Production

### ⚔️ Sub-tasks

- #94 
- #95
- #89 
- #90

**Comment by jordanpadams** [comment]
📆 03/2024 status: In work.

**Comment by jordanpadams** [comment]
📆 04/2024 status: In work. On schedule

**Comment by jordanpadams** [comment]
@ramesh-maddegoda do we think we will have this completed by the end of this sprint?

**Comment by ramesh-maddegoda** [comment]
> @ramesh-maddegoda do we think we will have this completed by the end of this sprint?

@jordanpadams , we will have this on MCP Test by the end of the sprint. But not on MCP Prod.

**Comment by ramesh-maddegoda** [comment]
> * As a user, I want to store a copy of my archive data in AWS Deep Archive / Glacier #73

Also, the glacier task is not available in DAGs yet.

**Comment by jordanpadams** [comment]
Copy. Thanks Ramesh.

**Comment by jordanpadams** [comment]
📆 05/2024 status: Scope increased requiring 2 sprint delay. Required delay in #54

**Comment by jordanpadams** [comment]
📆 06/2024 status: Significant delays and scope increase. No additional impact on schedule expected.

**Comment by jordanpadams** [comment]
📆 07/2024 status: Significant delays and scope increase. Deployment expected end of August. No impact on build as this was primary task for engineer for this build delivery.

**Comment by jordanpadams** [comment]
📆 09/2024 status: Terraform scrips completed. Baseline is mostly complete and deployed. Final iterations will occur in B15.1
